# -*- coding: utf-8 -*-
"""modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wuI-WBwc-XawlbN092xyidAbw_ToaqJW
"""

import json
import os
import google.generativeai as genai # Corrected import


try:
    from google.genai.types import GenerationConfig
except Exception:
    try:
        from google.genai import types as genai_types
        GenerationConfig = genai_types.GenerationConfig
    except Exception:
        GenerationConfig = None

# Set your GEMINI_API_KEY here
os.environ["GEMINI_API_KEY"] = "YOUR_API_KEY" # REPLACE WITH YOUR ACTUAL API KEY

GOOGLE_API_KEY = os.getenv("GEMINI_API_KEY")
if not GOOGLE_API_KEY:
    raise ValueError("Configura GEMINI_API_KEY en tus variables de entorno.")

genai.configure(api_key=GOOGLE_API_KEY);
gemini_model = genai.GenerativeModel('gemini-2.5-pro')

RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "impacto": {"type": "string", "enum": ["Alto", "Medio", "Bajo"]},
        "sentimiento": {"type": "string", "enum": ["Positivo", "Neutro", "Negativo"]},
        "justificacion_impacto": {"type": "string"},
        "justificacion_sentimiento": {"type": "string"}
    },
    "required": ["impacto", "sentimiento", "justificacion_impacto", "justificacion_sentimiento"]
}

def classify_news_with_gemini(news_text, news_id):

    MASTER_PROMPT = f"""
    Eres AgroSense, un analista experto en agronegocios.
    Sigue el esquema estrictamente.

    --- Noticia ---
    {news_text}
    """

    try:
        response = gemini_model.generate_content(
            contents=MASTER_PROMPT,
            generation_config=GenerationConfig(
                response_mime_type="application/json",
                response_schema=RESPONSE_SCHEMA
            )
        )

        raw = response.candidates[0].content[0].text
        result = json.loads(raw)
        result["news_id"] = news_id

        return result

    except Exception as e:
        print("Error:", e)
        print("Respuesta completa del modelo:", response)
        return None